name: "Build"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        run: |
          set -x
          git clone --recursive https://github.com/opa334/TrollStore ${{ github.workspace }}

      - name: Install Theos
        uses: Randomblock1/theos-action@v1

      - name: Install libarchive
        run: |
          brew install libarchive

      - name: Patch
        run: |
          sed -i.bak 's#com.opa334.TrollStore#com.apple.tips#g' ./Shared/TSUtil.h  && rm -f ./Shared/TSUtil.h.bak
          sed -i.bak 's#com.opa334.TrollStore#com.apple.tips#g' ./TrollStore/Resources/Info.plist  && rm -f ./TrollStore/Resources/Info.plist.bak
          sed -i.bak 's#build_installer15 build_installer64e##g' ./Makefile && rm -f ./Makefile.bak
          sed -i.bak 's#./TrollStore/.theos/obj/TrollStore.app/PersistenceHelper#./TrollStore/.theos/obj/TrollStore.app/PersistenceHelper && curl -L -o ./TrollStore/.theos/obj/TrollStore.app/PersistenceHelper https://github.com/opa334/TrollStore/releases/latest/download/PersistenceHelper_Embedded#g' ./Makefile && rm -f ./Makefile.bak

      - name: Build TrollStore
        run: |
          make

      - name: Generate timestamp version
        id: version
        run: |
          VERSION=$(date +%Y%m%d-%H%M%S)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release & Upload File
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: TrollStore(com.apple.tips) ${{ steps.version.outputs.version }}
          generate_release_notes: false
          files: ./_build/TrollStore.tar
